# Generated by Django 4.2.3 on 2023-08-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="short_name",
            field=models.CharField(max_length=20, verbose_name="Nombre corto"),
        ),
    ]
