# Generated by Django 4.2.3 on 2023-08-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skill",
            options={"verbose_name_plural": "habilidad empleado"},
        ),
    ]
