# Generated by Django 4.2.3 on 2023-08-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_alter_skill_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="NombreCompleto"
            ),
        ),
    ]
