name: manager

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t manager

      - name: Run Docker container
        run: docker run -d -p 8000:8000 manager
